language: node_js
script: npm run-script ci
after_script: codeclimate-test-reporter < coverage/lcov.info
node_js:
 - 'node'
 - '6'
 - '5'
 - '4'
sudo: false
addons:
    code_climate:
        repo_token: 6daf1df58d7bd37ca679d2e53201320fe4babe51334fb456dd35673d4a857d37